version: '3.7'

services:
  web:
    build: .
    command: python Bookmark_proj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bookmark_proj/Bookmark_proj
    ports:
      - 8000:8000

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bookmark_db

volumes:
  postgres_data:
