# Generated by Django 4.2.4 on 2023-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date time create')),
                ('date_change', models.DateTimeField(auto_now_add=True, verbose_name='Date time change')),
                ('links', models.ManyToManyField(related_name='collections', to='app_bookmarks.bookmark', verbose_name='Links')),
            ],
        ),
    ]
