# Generated by Django 4.2.4 on 2023-08-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_collections', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='links',
        ),
    ]
