# Generated by Django 4.2.4 on 2023-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('link', models.TextField(max_length=1000, verbose_name='Link')),
                ('type_link', models.CharField(db_index=True, max_length=50, verbose_name='Type link')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date time create')),
                ('date_change', models.DateTimeField(auto_now_add=True, verbose_name='Date time change')),
            ],
        ),
    ]
