# Generated by Django 4.2.4 on 2023-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmarks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Date time change'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Date time create'),
        ),
    ]
