# Generated by Django 4.2.4 on 2023-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmarks', '0005_alter_bookmark_title_alter_bookmark_type_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_change',
            field=models.DateTimeField(auto_now_add=True, max_length=500, verbose_name='Date time change'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, max_length=500, verbose_name='Date time create'),
        ),
    ]
