# Generated by Django 4.2.4 on 2023-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookmarks', '0007_alter_bookmark_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
